name: Build Stable

on:
  workflow_dispatch:
    inputs:

concurrency:
  group: stable
  cancel-in-progress: true

jobs:
  build:
    uses: ./.github/workflows/build-common.yml
    secrets: inherit
    with:
      image_tag: stable
